### ISSUE TITLE
iOS共享屏幕后控制台报错

### ISSUE THREAD

**Issue by JillZsy** [tencentyun/TUIRoomKit#134]
iOS共享屏幕后控制台报如下错误：
DemoApp[7283:1000296] [I][10-26/09:46:23.734+8.0][7283,77827][signal_manager.cc:708]@a700 Network: Signal: C2SResponse: C2SAcquireAuxVideoResponse, Seq:1268978562, Tinyid: 144115242130740731, ErrorCode:-101018

没有onScreenCaptureStarted回调，另一台手机没有接收到数据。这个该如何解决？

**Comment by AbySwifter** [comment]
该错误与共享屏幕无关，辛苦提供更进一步的日志。
