### ISSUE TITLE
m1 mac报错

### ISSUE THREAD

**Issue by adteven** [tencentyun/TUIRoomKit#174]
Release/trtc_electron_sdk.node' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)

**Comment by Tencent-Alice** [comment]
hi 根据您的问题 https://cloud.tencent.com/document/product/647/84237您参考这个文档集成的吗

**Comment by Tencent-Alice** [comment]
hi 根据您的问题  
https://cloud.tencent.com/document/product/647/84237您参考这个文档集成的吗

**Comment by Tencent-Alice** [comment]
hi 根据您的问题
https://cloud.tencent.com/document/product/647/84237您参考这个文档集成的吗  看报错是mach-o文件，不兼容的体系结构，需要arm64e。 技术问题 欢迎交流 Q2562367495 注明来意

**Comment by raingxm** [comment]
关于 Mac 下双架构 x86, arm64 双架构打包运行可参考 [文档](https://cloud.tencent.com/developer/article/2106645 ) , 如果 m1 本地开发环境可参考 [文档](https://www.jurnalanas.com/blog/node-js-mac-m1)
