### ISSUE TITLE
跳转链接有问题

### ISSUE THREAD

**Issue by beichen123-hub** [tencentyun/TUIRoomKit#274]
文档中的跳转 链接有问题。可能是文档编辑作者的在家办公的问题 留的网址是需要ioa远程办公访问的网址 所以除腾讯内部人员可以访问外其他人无法访问

**Comment by AbySwifter** [comment]
你好方便告知下是那篇文档不？我们修改一下

**Comment by beichen123-hub** [comment]
> 你好方便告知下是那篇文档不？我们修改一下

我已经反映给文档的同学了已经修改了
