### ISSUE TITLE
主会场开启全员静音后，刷新页面，分会场听不到主会场声音

### ISSUE THREAD

**Issue by chenfei4396** [tencentyun/TUIRoomKit#287]
主会场开启全员静音后，刷新页面，分会场听不到主会场声音，主会场本地麦克风显示未有声音状态

**Comment by Tencent-Alice** [comment]
HI 您使用demo也是如此吗 可以收集下相关报错信息1.终端信息及SDK版本号。2。SDKappid 3.接收方和发送发的userid 4.发生问题的具体时间点     技术问题 欢迎交流 Q2562367495 注明来意
