### ISSUE TITLE
web vue2 1.5.1   房主创建房间后  后进入的人只能听到声音看不见画面  

### ISSUE THREAD

**Issue by yy137523** [tencentyun/TUIRoomKit#342]
pc模式没问题 H5模式会出现这种问题  第一个进入的人是正常的  后进入的人只能听到声音 画面是全黑的

**Comment by zhangyuandai** [comment]
Does the issue still recur after upgrading RoomEngine? If so, please provide a log.

**Comment by Tencent-Alice** [comment]
您好。 您这块有复现的视频吗 可以发下哈， 另使用的版本是多少呢。 技术问题 欢迎交流 Q2562367495 注明来意
