### ISSUE TITLE
关于直播延时的疑问

### ISSUE THREAD

**Issue by sanxincao** [tencentyun/TUIRoomKit#388]
TRTC实时音视频产品和快直播的WEBRTC推流延迟上有什么区别

另外我按照腾讯云给出的文档
livePusher.startScreenCapture()
    .then(function () {
    livePusher.startPush('webrtc://1');
    })
    .catch(function (error) {
    console.log('打开摄像头失败: '+ error.toString());
    });
    // player-container-id 为播放器容器 ID，必须与 html 中一致
    var player = TCPlayer('player-container-id', {
        sources: [{
          src: 'webrtc://www.****/test',
        }],
        licenseUrl: 'https://license********', // 参考准备工作部分，在视立方控制台申请 license 后可获得 licenseUrl
    });

    player.on('webrtcevent', function(event) {
   // 从回调参数 event 中获取事件状态码及相关数据
   console.log(event);
简单实现了快直播的功能，却发现与腾讯云web推流的示例差别很大，腾讯云官方的示例demo播放非常流畅，而且感受不到延迟，而我实现的demo画面偶尔有一些卡顿，而且延迟稍微比腾讯云官网的示例demo高一点点（能感觉出来操作上的延迟），对此您有什么建议的改进方向我这就去查，谢谢您了

**Comment by lixin0** [comment]
你好，你可以使用 https://cloud.tencent.com/document/product/647/63830 TUIPusher&TUIPlayer 在主播端共享一个带有时间戳的视频体验实时音视频（TRTC超低延时观看）和快直播的差异。

关于快直播延时较大的问题，可以前往 https://cloud.tencent.com/document/product/454 直播 SDK 官网进行客服咨询。
