### ISSUE TITLE
iOS-原OC项目集成后，总是报错'SSZipArchive.h' file not found，请问可能是什么原因，我该从哪里解决呢？

### ISSUE THREAD

**Issue by PreSwift** [tencentyun/TUIRoomKit#57]
<img width="1878" alt="image" src="https://user-images.githubusercontent.com/11828021/171072504-d95c3771-2ca5-4d56-b12e-0da92c8dedb7.png">

**Comment by AbySwifter** [comment]
新版的TUIRoomKit已解决该问题，建议升级
