### ISSUE TITLE
多人视频会议无聊天功能

### ISSUE THREAD

**Issue by likeconan** [tencentyun/TUIRoomKit#66]
进入多人视频会议后，无聊天功能，麻烦能提供像electron一样类似的聊天界面功能

**Comment by gu6541515** [comment]
提供了发送消息的API，可以自己实现方法调用将文字显示在想要显示的地方（sendChatMessage）
![image](https://user-images.githubusercontent.com/18611493/174543266-c719bbc1-93df-414a-b35d-b344d4939e5a.png)

**Comment by gu6541515** [comment]
我也提了不少问题，没人回

**Comment by lixin0** [comment]
> 进入多人视频会议后，无聊天功能，麻烦能提供像electron一样类似的聊天界面功能

你好 请问是哪个端呢

**Comment by AbySwifter** [comment]
已添加更新
