### ISSUE TITLE
electron和android，ios端不互通

### ISSUE THREAD

**Issue by likeconan** [tencentyun/TUIRoomKit#81]
以electron端创建房间，android和ios端作为成员加入房间，

加入后，electron无法看到android和ios新增的成员，并且无法看到和听到android，ios端的音视频流；

成员可以在手机端看到electron共享的屏幕和摄像头。

成员可以被全员禁麦

请问如何解决其互通问题？

**Comment by AbySwifter** [comment]
新版本已解决该问题，建议尝试TUIRoomKit最新版
