### ISSUE TITLE
当有其他人员加入到直播间时，ios端的已加入用户共享屏幕内容会消失1s，然后再重新渲染成功

### ISSUE THREAD

**Issue by likeconan** [tencentyun/TUIRoomKit#89]
用户A，已经加入直播间，正常观看主播共享内容
用户B，加入或退出直播间，用户A页面会变黑，共享屏幕内容消失，页面重新渲染，1s后，页面显示正常

看源码是由于下面代码造成
<img width="600" alt="image" src="https://user-images.githubusercontent.com/12960160/180952506-85af39b7-0299-42c1-a594-91b9da23cc97.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/12960160/180952545-e564d3f2-4898-4d10-8671-bdf4d33d63e0.png">

**Comment by AbySwifter** [comment]
感谢反馈，已反馈到对应研发同学修复
